### ISSUE TITLE
Can't create wav file with TTS

### ISSUE THREAD

**Issue by adelriosantiago** [antirek/google-speech#1]
I'm trying to use the TTS feature with the sample code but all I get is a MP3 file that with a few milliseconds of noise.

Am I missing something? Is the TTS API still working?

**Comment by antirek** [comment]
TTS API work fine.
Try go to http://translate.google.com/translate_tts?q=hello&ie=UTF-8&tl=en - if you listen - all ok.

What contain your MP3 file? Binary data or HTML code?

**Comment by adelriosantiago** [comment]
You are right!, I was getting off the quota limits, that's strange I had not done any API call ever before... 

Anyway it is solved not, thanks.

**Comment by antirek** [comment]
try now 0.0.5, may be it help https://github.com/antirek/google-speech/commit/2067f14a5142b2a084b39a4e9a8a08938f54392e
